FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    g++ iptables \
    && rm -rf /var/lib/apt/lists/*

COPY coord.cpp /app/coord.cpp
COPY parameters.h /app/parameters.h
RUN g++ -std=c++20 /app/coord.cpp -o /app/coord

COPY coord.sh /app/coord.sh

WORKDIR /app

CMD ["./coord.sh"]