FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    g++ iptables iproute2 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8081 8082 8083

CMD ["python", "-u", "main.py"]
